import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/Components/Header";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "react-hot-toast";
import AuthToast from "@/Components/AuthToast";
import { toastConfig } from "@/lib/toastConfig";
import StoreProvider from "./StoreProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "RPG Habit Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen w-full`}
      >
        <StoreProvider>
          <div className="bg-gradient-to-b from-gray-900 via-gray-800 to-gray-900 max-w-full h-screen flex flex-col">
            <SessionProvider>
              <Toaster
                position="bottom-right"
                reverseOrder={false}
                toastOptions={toastConfig}
              />

              <AuthToast />
              <Header />
              <main className="h-[calc(100vh-75px)] overflow-hidden">
                {children}
              </main>
            </SessionProvider>
          </div>
        </StoreProvider>
      </body>
    </html>
  );
}
